<?php
/**
 * Extend Warranty
 *
 * @author      Extend Magento Team <magento@extend.com>
 * @category    Extend
 * @package     Warranty
 * @copyright   Copyright (c) 2023 Extend Inc. (https://www.extend.com/)
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Extend\Warranty\Block\Sales\Order\Email\Items\WarrantyItem  */

/** @var $_item \Magento\Sales\Model\Order\Item */

    $_item = $block->getItem();
    $_order = $_item->getOrder();
    $_imageHelper = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Catalog\Helper\Image');
?>
<tr>
    <td class="item-info<?= ($block->getItemOptions() ? ' has-extra' : '') ?>">
        <div style="width:100%; display:flex;">
            <div style="padding:15px 15px; float:left;margin-right:10px; text-align:center; display:inline-block; vertical-align:center;">
                <img src="<?= $_imageHelper->init($_item->getProduct(), 'small_image', ['type'=>'small_image'])->keepAspectRatio(true)->resize('65','65')->getUrl();?>" alt="<?= __('Product Image');?>" style="margin:auto; display:table; width:65px;">
            </div>
            <div style="float:left; width:190px;">


        <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
        <p class="sku"><?= $block->escapeHtml(__('SKU')) ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
        <?php if ($associatedItemName = $block->getAssociatedItemName()) : ?>
            <p class="associated-product-name"><?= $block->escapeHtml(__('Covered product')) ?>: <?= $block->escapeHtml($associatedItemName) ?></p>
        <?php endif;?>
        <?php if ($block->getItemOptions()) : ?>
            <dl class="item-options">
                <?php foreach ($block->getItemOptions() as $option) : ?>
                    <dt><strong><em><?= $block->escapeHtml($option['label']) ?></em></strong></dt>
                    <dd>
                        <?= /* @noEscape */  nl2br($block->escapeHtml($option['value'])) ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
           </div>
        </div>
    </td>

    <td class="item-price" style="text-align:center;">
        <?= /* @noEscape */ $block->getItemPrice($_item) ?>
    </td>

    <td class="item-qty" style="text-align:center;" ><?= (float) $_item->getQtyOrdered() ?></td>


    <td class="item-total" style="text-align:center;"><?= (float) $_item->getRowTotal() ?></td>
</tr>
<?php if ($_item->getGiftMessageId()
    && $_giftMessage = $this->helper(\Magento\GiftMessage\Helper\Message::class)
        ->getGiftMessage($_item->getGiftMessageId())
) : ?>
    <tr>
        <td colspan="3" class="item-extra">
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= $block->escapeHtml(__('Gift Message')) ?></h3>
                        <strong><?= $block->escapeHtml(__('From:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br /><strong><?= $block->escapeHtml(__('To:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br /><strong><?= $block->escapeHtml(__('Message:')) ?></strong>
                        <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
<?php endif; ?>
